name: Deploy action
description: 'set node version and node sha before committing changes and deploy version'

inputs:
  PAT:
    description: 'PAT from repo'
    required: true
  NAMESPACE:
    description: 'Namespace'
    required: true
    default: ''
  NAME:
    description: 'Name'
    required: false
    default: ''
  SERVICES:
    description: 'Services'
    required: false
    default: ''
  version:
    description: 'build.outputs.version'
    required: true
    default: ''
  env:
    description: 'build.outputs.env'
    required: true
    default: 'stage'
  SLACK_TOKEN:
    description: 'slack token'
    required: false
    default: ''
  SLACK_CHANNEL:
    description: 'slack channel'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v6
    with:
      repository: entrecode/ec.argocd
      token: ${{ inputs.PAT }}
      ref: main

  - name: run yq eval node
    run: |
      if [[ -n ${SERVICES} ]]; then
        IFS="," read -r -a SRV <<< "${SERVICES}"
        for I in "${SRV[@]}"; do
          IFS=":" read -r SERVICE YQ_PATH <<< "${I}"
          YQ_PATH=${YQ_PATH:-.node}
          VERSION=${YQ_PATH}.version GITSHA=${YQ_PATH}.gitsha yq eval -i 'eval(strenv(VERSION)) = "${{ inputs.version }}" | eval(strenv(GITSHA)) = "${{ github.sha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${SERVICE}/version.yaml  
        done
      fi
      if [[ -n ${NAME} ]]; then
        yq eval -i '.node.version = "${{ inputs.version }}" | .node.gitsha = "${{ github.sha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME }}/version.yaml  
      fi
    shell: bash
    env:
      SERVICES: ${{ inputs.SERVICES }}
      NAME: ${{ inputs.NAME }}

  - name: Commit changes
    run: |
      export GITHUB_EVENT_PUSHER_NAME=${{ github.event.pusher.name }}
      export GITHUB_EVENT_PUSHER_EMAIL=${{ github.event.pusher.email }}
      git config --global user.name "${GITHUB_EVENT_PUSHER_NAME:-${GITHUB_ACTOR:-github-actions[bot]}}"
      git config --global user.email "${GITHUB_EVENT_PUSHER_EMAIL:-41898282+github-actions[bot]}@users.noreply.github.com}"
      
      if [[ -n ${NAME} ]]; then
        MESSAGE+="[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${NAME}] Deploy ${{ inputs.version }}"
        MESSAGE+=$'\n'
      fi
      if [[ -n ${SERVICES} ]]; then
        IFS="," read -r -a SRV <<< "${SERVICES}"
        for I in "${SRV[@]}"; do
          IFS=":" read -r SERVICE YQ_PATH <<< "${I}"
          MESSAGE+="[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${SERVICE}] Deploy ${{ inputs.version }}"
          MESSAGE+=$'\n'
        done
      fi

      if ! git diff --quiet; then
        git commit -am "${MESSAGE}"
      else
        echo "No changes – Commit is skipped."
        exit 0
      fi
      git pull --rebase
      git push
    shell: bash
    env:
      SERVICES: ${{ inputs.SERVICES }}
      NAME: ${{ inputs.NAME }}


  - name: Hector slack Notifications with name as input
    if: inputs.NAMESPACE == 'hector' && inputs.env == 'prod' && inputs.SLACK_TOKEN != '' && inputs.SLACK_CHANNEL != '' && inputs.NAME != '' && inputs.SERVICES == ''
    uses: slackapi/slack-github-action@v2
    with:
      method: chat.postMessage
      token: ${{ inputs.SLACK_TOKEN }}
      payload: |
        channel: ${{ inputs.SLACK_CHANNEL }}
        attachments:
          - color: "28a745"
            fields:
              - value: "Neue Version ${{ inputs.version }} von ${{ inputs.NAME }} ausgerollt"

  - name: Set Service Name
    if: inputs.NAME == '' && inputs.SERVICES != ''
    run: |
      if [[ -n ${SERVICES} ]]; then
        IFS="," read -r -a SRV <<< "${SERVICES}"
        echo "SERVICE_NAME=${SRV[0]}" >> $GITHUB_ENV
      fi
    shell: bash
    env:
      SERVICES: ${{ inputs.SERVICES }}

  - name: Hector slack Notifications with services as input
    if: inputs.NAMESPACE == 'hector' && inputs.env == 'prod' && inputs.SLACK_TOKEN != '' && inputs.SLACK_CHANNEL != '' && inputs.NAME == '' && inputs.SERVICES != ''
    uses: slackapi/slack-github-action@v2
    with:
      method: chat.postMessage
      token: ${{ inputs.SLACK_TOKEN }}
      payload: |
        channel: ${{ inputs.SLACK_CHANNEL }}
        attachments:
          - color: "28a745"
            fields:
              - value: "Neue Version ${{ inputs.version }} von ${{ env.SERVICE_NAME }} ausgerollt"
