name: Deploy action
description: ''

inputs:
  apiversion: 
    description: 'api-version'
    required: false
    default: ''
  apigitsha: 
    description: 'api-gitsha'
    required: false
    default: ''
  workerversion:
    description: 'worker-version'
    required: false
    default: ''
  workergitsha:
    description: 'worker-gitsha'
    required: false
    default: ''
  nodeversion:
    description: 'node-version'
    required: false
    default: ''
  nodegitsha:
    description: 'node-gitsha'
    required: false
    default: ''
  NAMESPACE:
    description: 'Namespace'
    required: true
    default: ''
  NAME:
    description: 'Name'
    required: true
    default: ''
  env:
    description: 'env'
    required: true
    default: ''
  pushername:
    description: 'pusher namen'
    required: true
    default: ''
  pusheremail:
    description: 'pusher email'
    required: true
    default: ''
  deployversion:
    description: 'deploy version'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
  - name: run yq eval node
    if: inputs.nodeversion != '' && inputs.nodegitsha != ''
    run: yq eval -i '.node.version = "${{ inputs.nodeversion }}" | .node.gitsha = "${{ inputs.nodegitsha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME}}/version.yaml  
    shell: bash

  - name: run yq eval api
    if: inputs.apiversion != '' && inputs.apigitsha != ''  
    run: yq eval -i '.api.version = "${{ inputs.apiversion }}" | .api.gitsha = "${{ inputs.apigitsha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME}}/version.yaml     
    shell: bash
  
  - name: run yq eval worker
    if: inputs.workerversion != '' && inputs.workergitsha != ''
    run: yq eval -i '.worker.version = "${{ inputs.workerversion }}" | .worker.gitsha = "${{ inputs.workergitsha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME}}/version.yaml
    shell: bash
  
  - name: Commit changes
    run: |
      git config --global user.name ${{ inputs.pushername }}
      git config --global user.email ${{ inputs.pusheremail }}
      git commit -am "[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME }}] Deploy ${{ inputs.deployversion }}"
      git push
    shell: bash