name: Deploy action
description: 'set node version and node sha before committing changes and deploy version'

inputs:
  version: 
    description: 'build.outputs.version'
    required: true
    default: ''
  NAMESPACE:
    description: 'Namespace'
    required: true
    default: ''
  NAME:
    description: 'Name'
    required: true
    default: ''
  env:
    description: 'build.outputs.env'
    required: true
    default: 'stage'

runs:
  using: 'composite'
  steps:
  - name: run yq eval node
    run: yq eval -i '.node.version = "${{ inputs.version }}" | .node.gitsha = "${{ github.sha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME}}/version.yaml  
    shell: bash

  - name: Commit changes
    run: |
      git config --global user.name ${{ github.event.pusher.name }}
      git config --global user.email ${{ github.event.pusher.email }}
      git commit -am "[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME }}] Deploy ${{ inputs.version }}"
      git push
    shell: bash