name: Deploy action
description: 'set node version and node sha before committing changes and deploy version'

inputs:
  PAT:
    description: 'PAT from repo'
    required: true
  NAMESPACE:
    description: 'Namespace'
    required: true
    default: ''
  NAME:
    description: 'Name'
    required: false
    default: ''
  SERVICES:
    description: 'Services'
    required: false
    default: ''
  version:
    description: 'build.outputs.version'
    required: true
    default: ''
  env:
    description: 'build.outputs.env'
    required: true
    default: 'stage'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      repository: entrecode/ec.argocd
      token: ${{ inputs.PAT }}
      ref: main

  - name: run yq eval node
    run: |
      if [[ -n ${SERVICES} ]]; then
        IFS="," read -r -a SRV <<< "${SERVICES}"
        for I in "${SRV[@]}"; do
          IFS=":" read -r SERVICE YQ_PATH <<< "${I}"
          YQ_PATH=${YQ_PATH:-.node}
          VERSION=${YQ_PATH}.version
          GITSHA=${YQ_PATH}.gitsha
          yq eval -i 'eval(VERSION) = "${{ inputs.version }}" | eval(GITSHA) = "${{ github.sha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${SERVICE}/version.yaml  
        done
      fi
      if [[ -n ${NAME} ]]; then
        yq eval -i '.node.version = "${{ inputs.version }}" | .node.gitsha = "${{ github.sha }}"' apps/${{ inputs.env }}/${{ inputs.NAMESPACE }}/${{ inputs.NAME }}/version.yaml  
      fi
    shell: bash
    env:
      SERVICES: ${{ inputs.SERVICES }}
      NAME: ${{ inputs.NAME }}

  - name: Commit changes
    run: |
      git config --global user.name ${{ github.event.pusher.name }}
      git config --global user.email ${{ github.event.pusher.email }}
      
      if [[ -n ${NAME} ]]; then
        MESSAGE+="[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${NAME}] Deploy ${{ inputs.version }}"
        MESSAGE+=$'\n'
      fi
      if [[ -n ${SERVICES} ]]; then
        IFS="," read -r -a SRV <<< "${SERVICES}"
        for I in "${SRV[@]}"; do
          IFS=":" read -r SERVICE PATH <<< "${I}"
          MESSAGE+="[${{ inputs.env }}/${{ inputs.NAMESPACE }}/${SERVICE}] Deploy ${{ inputs.version }}"
          MESSAGE+=$'\n'
        done
      fi
      
      git commit -am "${MESSAGE}"
      git pull --rebase
      git push
    shell: bash
    env:
      SERVICES: ${{ inputs.SERVICES }}
      NAME: ${{ inputs.NAME }}
